export { default as Ecommerce } from '../PatientDashboard/Ecommerce';
//export { default as Appointment } from './Appointment';
export { default as Kanban } from '../PatientDashboard/Kanban';
//export { default as Orders } from './Orders';
export { default as Notification} from '../PatientDashboard/Notification';
export { default as Doctor } from '../PatientDashboard/Doctor';
export { default as Editor } from '../PatientDashboard/Editor';
export { default as Customers } from '../PatientDashboard/Customers';
//export { default as ColorPicker } from './ColorPicker';
export { default as Calendar } from '../PatientDashboard/Calendar';
//export { default as Area } from './Charts/Area';
//export { default as Bar } from './Charts/Bar';
//export { default as ColorMapping } from './Charts/ColorMapping';
//export { default as Financial } from './Charts/Financial';
//export { default as Line } from './Charts/Line';
//export { default as Pie } from './Charts/Pie';
//export { default as Pyramid } from './Charts/Pyramid';
//export { default as Stacked } from './Charts/Stacked';
export { default as Appointment } from '../PatientDashboard/Appointment';
export { default as Records} from '../PatientDashboard/Records';
export { default as Prescription } from '../PatientDashboard/Prescription';
export { default as Review} from '../PatientDashboard/Review';
export { default as Emergency} from '../PatientDashboard/Emergency';
export { default as Consultation} from '../PatientDashboard/Consultation';
export { default as Billing}from '../PatientDashboard/Billing';
export { default as QnA } from '../PatientDashboard/QnA';
export { default as Remainder} from '../PatientDashboard/Remainder';
export { default as Patient_Dashboard} from '../PatientDashboard/Patient_Dashboard';

