export { default as Ecommerce } from '../DoctorDashboard/Ecommerce';
//export { default as Appointment } from './Appointment';
export { default as Kanban } from '../DoctorDashboard/Kanban';
//export { default as Orders } from './Orders';
export { default as Notification} from '../DoctorDashboard/Notification';
export { default as Doctor } from '../DoctorDashboard/Doctor';
export { default as Editor } from '../DoctorDashboard/Editor';
export { default as Customers } from '../DoctorDashboard/Customers';
//export { default as ColorPicker } from './ColorPicker';
export { default as Calendar } from '../DoctorDashboard/Calendar';
//export { default as Area } from './Charts/Area';
//export { default as Bar } from './Charts/Bar';
//export { default as ColorMapping } from './Charts/ColorMapping';
//export { default as Financial } from './Charts/Financial';
//export { default as Line } from './Charts/Line';
//export { default as Pie } from './Charts/Pie';
//export { default as Pyramid } from './Charts/Pyramid';
//export { default as Stacked } from './Charts/Stacked';
export { default as Appointment } from '../DoctorDashboard/Appointment';
export { default as Records} from '../DoctorDashboard/Records';
export { default as Prescription } from '../DoctorDashboard/Prescription';
export { default as Review} from '../DoctorDashboard/Review';
export { default as Emergency} from '../DoctorDashboard/Emergency';
export { default as Consultation} from '../DoctorDashboard/Consultation';
export { default as Billing}from '../DoctorDashboard/Billing';
export { default as QnA } from '../DoctorDashboard/QnA';
export { default as Remainder} from '../DoctorDashboard/Remainder';
export { default as Doctor_Dashboard} from '../DoctorDashboard/Doctor_Dashboard';
export { default as Inventory} from '../DoctorDashboard/Inventory';
export { default as Doctor_Profile } from '../DoctorDashboard/Doctor_Profile';
export { default as Clinic} from '../DoctorDashboard/Clinic';
export { default as Finances} from'../DoctorDashboard/Finances';

